services:
  webdav:
    image: vblechta/webdav
    container_name: webdav
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /path/to/data/:/media
    environment:
      UID: 33
      GID: 33
      USERNAME: ${NAME}
      PASSWORD: ${WEBDAV_PASSWORD}
